### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by zmeulDev** [akbarpulatov/flutter_awesome_select#40]
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building S2ChipTheme(dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#1ff2b]]):
Null check operator used on a null value

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/...../lib/main.dart:54:12
When the exception was thrown, this was the stack: 
#0      S2ChipTheme.build (package:awesome_select/src/chip_theme.dart:86:73)
#1      StatelessElement.build (package:flutter/src/widgets/framework.dart:4827:28)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#7      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#8      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (157 frames)
#165    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#166    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#167    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (33 frames)
#200    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#201    Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
#202    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1243:37)
#203    SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1148:35)
#204    SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1206:9)
#205    SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1126:7)
#206    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#207    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#208    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#209    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#210    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#211    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#212    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#213    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5787:32)
#214    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#215    _ViewportElement.update (package:flutter/src/widgets/viewport.dart:228:11)
#216    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#217    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#219    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#220    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#221    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#222    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#223    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#226    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#227    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#228    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#229    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#230    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#233    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#234    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#235    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#236    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#237    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#238    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#239    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#240    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#241    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#242    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#243    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#244    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#245    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#246    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#247    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#248    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#249    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#250    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#251    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#252    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#253    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#254    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#255    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#256    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#257    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#258    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#259    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#260    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#261    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#262    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#263    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#264    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#265    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#266    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#267    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#268    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#269    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#270    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#271    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#272    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#273    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#274    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#275    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#276    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#277    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#278    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#279    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#280    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#281    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#282    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#283    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#284    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#285    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#286    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#287    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#288    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#289    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#290    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#291    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#292    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#293    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#294    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#295    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#296    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#297    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#298    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#299    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#300    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#301    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#302    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#303    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#304    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#305    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#306    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#307    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#308    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#309    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#310    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#311    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#312    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#313    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#314    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#315    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#316    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#317    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#318    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#319    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#320    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#321    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5787:32)
#322    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#323    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#324    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#325    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#326    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#327    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#328    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#329    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#330    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#331    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#332    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#333    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#334    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#335    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#336    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#337    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#338    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#339    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#340    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#341    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#342    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#343    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#344    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#345    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#346    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#347    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#348    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#349    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#350    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#354    _invoke (dart:ui/hooks.dart:151:10)
#355    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#356    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale en-RO)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by zmeulDev** [comment]
This occurs only with:

choiceType: S2ChoiceType.chips,
choiceGrouped: true,
